//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Settings/Input System/MyInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/Input System/MyInputSystem.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MyInputSystem: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MyInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MyInputSystem"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""6673c117-0bef-44a6-8ca8-6cc98fc5b058"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""25b32c62-9ba2-4c8d-9cf8-f22b104e7db9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""5253154b-4cbf-46e4-93cf-eedc3ef8adc7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""IsSprint"",
                    ""type"": ""Button"",
                    ""id"": ""6305751d-769d-46e0-a9a6-d8e4926d2e02"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsJump"",
                    ""type"": ""Button"",
                    ""id"": ""54b63d76-545f-4acc-b008-1540de1c5701"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""1ea27cd6-4290-4e47-bea0-f63386dfb75b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3e54c2e5-6307-41fe-98c8-034891630143"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4e0efef0-99d5-48d2-8aab-11c0a06a6afe"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""91f24831-a427-4429-8a34-1ce9a684ccbb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""09fa44d3-6bd4-4c7f-9833-7609407b3701"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6760f5de-e12b-4757-aeae-53e871ab1eed"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91f5a823-6b86-493f-896d-7e39ea9f35dc"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a6c5bb4-deb5-4317-afed-a99e6ab04b75"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerCombat"",
            ""id"": ""f4103dab-0da6-49ac-81dd-8b5c738cb853"",
            ""actions"": [
                {
                    ""name"": ""IsFire"",
                    ""type"": ""Button"",
                    ""id"": ""d86dc43c-295d-47c5-967b-c49f558cbaf3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsAim"",
                    ""type"": ""Button"",
                    ""id"": ""4230afca-4e1e-4c28-adb1-7de15016f369"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsReload"",
                    ""type"": ""Button"",
                    ""id"": ""962b7449-ae42-45a3-a24b-62ce17ebccc8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""2ca6de8e-e798-477d-9e87-f25723984554"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e1537fe8-ed02-458d-9e6b-7481defeab0b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsFire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fe1e9aa-33d4-40a6-a87c-c20b91a46108"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3999fee6-2338-4c18-9cd9-f75c7275b2cb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsReload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4288f6f5-ba03-4f0b-8d67-292b7ab01c47"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerSkill"",
            ""id"": ""cb54b3b1-5852-4091-a318-7e16f855c2b7"",
            ""actions"": [
                {
                    ""name"": ""IsSkill1"",
                    ""type"": ""Button"",
                    ""id"": ""a308c293-9df7-4083-87f0-c9bf0fec5612"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSkill2"",
                    ""type"": ""Button"",
                    ""id"": ""f4967418-f5a6-4f9c-8606-21a7dba59f2d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSkill3"",
                    ""type"": ""Button"",
                    ""id"": ""10058e4d-8b98-4ac6-a084-cb67cb08441b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSkill4"",
                    ""type"": ""Button"",
                    ""id"": ""4a524b72-64d8-4091-b26a-645c7b3fb02d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d94b3e5c-2c41-409e-b3bc-abdbff0b7265"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSkill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7aaea61c-4aef-4d17-b396-8f81c7f6d961"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSkill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee982840-fc4d-4658-bc0d-ccc89bfe9344"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSkill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340dffed-9f07-4a68-a1e6-8caefc814b84"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSkill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerTeam"",
            ""id"": ""042c9cf2-a2a7-442b-a1aa-79ec3810ad79"",
            ""actions"": [
                {
                    ""name"": ""IsSwitchAI1"",
                    ""type"": ""Button"",
                    ""id"": ""706ac1d8-beea-42b7-81f6-e23a89e0648e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSwitchAI2"",
                    ""type"": ""Button"",
                    ""id"": ""00566009-9ba7-4bb5-9acd-c978e9bc9888"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSwitchAI3"",
                    ""type"": ""Button"",
                    ""id"": ""0ed50010-3a29-45e4-a86d-567cd991edf7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSwitchAI4"",
                    ""type"": ""Button"",
                    ""id"": ""db8c3b70-e387-4f50-8eb4-306f075b3079"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsSwitchNextCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""eecd5709-e33b-4c33-9438-d81a41c4a6ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bb193a75-1746-4a17-bcb1-6a99cf7b5547"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSwitchAI1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a974e71-24b3-4df0-b82d-249c78daeb34"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSwitchAI2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8fa594f-07bc-4ff6-9231-ee0b635d2406"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSwitchAI3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01d4c97e-3585-4c7d-855e-e9b63e6b5196"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSwitchAI4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""663753de-1ffa-4aa8-9e9e-19236838be6e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsSwitchNextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerInteraction"",
            ""id"": ""1f484e9d-23ad-4133-a85c-253079ef2dc4"",
            ""actions"": [
                {
                    ""name"": ""IsPickUp"",
                    ""type"": ""Button"",
                    ""id"": ""4d5d6982-f85d-4c98-b2bd-4453c87f0128"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IsOpenOrCloseBag"",
                    ""type"": ""Button"",
                    ""id"": ""116bcdf3-26bd-4432-ba7f-1277be03ae12"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""439ca1ed-5ba7-4bb3-b18f-53be7a7ab7a3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsPickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e90f248-f0a6-4da1-969a-4f17a281d496"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IsOpenOrCloseBag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_Move = m_PlayerMovement.FindAction("Move", throwIfNotFound: true);
        m_PlayerMovement_Look = m_PlayerMovement.FindAction("Look", throwIfNotFound: true);
        m_PlayerMovement_IsSprint = m_PlayerMovement.FindAction("IsSprint", throwIfNotFound: true);
        m_PlayerMovement_IsJump = m_PlayerMovement.FindAction("IsJump", throwIfNotFound: true);
        // PlayerCombat
        m_PlayerCombat = asset.FindActionMap("PlayerCombat", throwIfNotFound: true);
        m_PlayerCombat_IsFire = m_PlayerCombat.FindAction("IsFire", throwIfNotFound: true);
        m_PlayerCombat_IsAim = m_PlayerCombat.FindAction("IsAim", throwIfNotFound: true);
        m_PlayerCombat_IsReload = m_PlayerCombat.FindAction("IsReload", throwIfNotFound: true);
        m_PlayerCombat_SwitchWeapon = m_PlayerCombat.FindAction("SwitchWeapon", throwIfNotFound: true);
        // PlayerSkill
        m_PlayerSkill = asset.FindActionMap("PlayerSkill", throwIfNotFound: true);
        m_PlayerSkill_IsSkill1 = m_PlayerSkill.FindAction("IsSkill1", throwIfNotFound: true);
        m_PlayerSkill_IsSkill2 = m_PlayerSkill.FindAction("IsSkill2", throwIfNotFound: true);
        m_PlayerSkill_IsSkill3 = m_PlayerSkill.FindAction("IsSkill3", throwIfNotFound: true);
        m_PlayerSkill_IsSkill4 = m_PlayerSkill.FindAction("IsSkill4", throwIfNotFound: true);
        // PlayerTeam
        m_PlayerTeam = asset.FindActionMap("PlayerTeam", throwIfNotFound: true);
        m_PlayerTeam_IsSwitchAI1 = m_PlayerTeam.FindAction("IsSwitchAI1", throwIfNotFound: true);
        m_PlayerTeam_IsSwitchAI2 = m_PlayerTeam.FindAction("IsSwitchAI2", throwIfNotFound: true);
        m_PlayerTeam_IsSwitchAI3 = m_PlayerTeam.FindAction("IsSwitchAI3", throwIfNotFound: true);
        m_PlayerTeam_IsSwitchAI4 = m_PlayerTeam.FindAction("IsSwitchAI4", throwIfNotFound: true);
        m_PlayerTeam_IsSwitchNextCharacter = m_PlayerTeam.FindAction("IsSwitchNextCharacter", throwIfNotFound: true);
        // PlayerInteraction
        m_PlayerInteraction = asset.FindActionMap("PlayerInteraction", throwIfNotFound: true);
        m_PlayerInteraction_IsPickUp = m_PlayerInteraction.FindAction("IsPickUp", throwIfNotFound: true);
        m_PlayerInteraction_IsOpenOrCloseBag = m_PlayerInteraction.FindAction("IsOpenOrCloseBag", throwIfNotFound: true);
    }

    ~@MyInputSystem()
    {
        UnityEngine.Debug.Assert(!m_PlayerMovement.enabled, "This will cause a leak and performance issues, MyInputSystem.PlayerMovement.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerCombat.enabled, "This will cause a leak and performance issues, MyInputSystem.PlayerCombat.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerSkill.enabled, "This will cause a leak and performance issues, MyInputSystem.PlayerSkill.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerTeam.enabled, "This will cause a leak and performance issues, MyInputSystem.PlayerTeam.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerInteraction.enabled, "This will cause a leak and performance issues, MyInputSystem.PlayerInteraction.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_Move;
    private readonly InputAction m_PlayerMovement_Look;
    private readonly InputAction m_PlayerMovement_IsSprint;
    private readonly InputAction m_PlayerMovement_IsJump;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerMovement".
    /// </summary>
    public struct PlayerMovementActions
    {
        private @MyInputSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerMovementActions(@MyInputSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerMovement/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_PlayerMovement_Move;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMovement/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_PlayerMovement_Look;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMovement/IsSprint".
        /// </summary>
        public InputAction @IsSprint => m_Wrapper.m_PlayerMovement_IsSprint;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMovement/IsJump".
        /// </summary>
        public InputAction @IsJump => m_Wrapper.m_PlayerMovement_IsJump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerMovementActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerMovementActions" />
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @IsSprint.started += instance.OnIsSprint;
            @IsSprint.performed += instance.OnIsSprint;
            @IsSprint.canceled += instance.OnIsSprint;
            @IsJump.started += instance.OnIsJump;
            @IsJump.performed += instance.OnIsJump;
            @IsJump.canceled += instance.OnIsJump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerMovementActions" />
        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @IsSprint.started -= instance.OnIsSprint;
            @IsSprint.performed -= instance.OnIsSprint;
            @IsSprint.canceled -= instance.OnIsSprint;
            @IsJump.started -= instance.OnIsJump;
            @IsJump.performed -= instance.OnIsJump;
            @IsJump.canceled -= instance.OnIsJump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerMovementActions.UnregisterCallbacks(IPlayerMovementActions)" />.
        /// </summary>
        /// <seealso cref="PlayerMovementActions.UnregisterCallbacks(IPlayerMovementActions)" />
        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerMovementActions.AddCallbacks(IPlayerMovementActions)" />
        /// <seealso cref="PlayerMovementActions.RemoveCallbacks(IPlayerMovementActions)" />
        /// <seealso cref="PlayerMovementActions.UnregisterCallbacks(IPlayerMovementActions)" />
        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerMovementActions" /> instance referencing this action map.
    /// </summary>
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);

    // PlayerCombat
    private readonly InputActionMap m_PlayerCombat;
    private List<IPlayerCombatActions> m_PlayerCombatActionsCallbackInterfaces = new List<IPlayerCombatActions>();
    private readonly InputAction m_PlayerCombat_IsFire;
    private readonly InputAction m_PlayerCombat_IsAim;
    private readonly InputAction m_PlayerCombat_IsReload;
    private readonly InputAction m_PlayerCombat_SwitchWeapon;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerCombat".
    /// </summary>
    public struct PlayerCombatActions
    {
        private @MyInputSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerCombatActions(@MyInputSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerCombat/IsFire".
        /// </summary>
        public InputAction @IsFire => m_Wrapper.m_PlayerCombat_IsFire;
        /// <summary>
        /// Provides access to the underlying input action "PlayerCombat/IsAim".
        /// </summary>
        public InputAction @IsAim => m_Wrapper.m_PlayerCombat_IsAim;
        /// <summary>
        /// Provides access to the underlying input action "PlayerCombat/IsReload".
        /// </summary>
        public InputAction @IsReload => m_Wrapper.m_PlayerCombat_IsReload;
        /// <summary>
        /// Provides access to the underlying input action "PlayerCombat/SwitchWeapon".
        /// </summary>
        public InputAction @SwitchWeapon => m_Wrapper.m_PlayerCombat_SwitchWeapon;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerCombat; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerCombatActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerCombatActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerCombatActions" />
        public void AddCallbacks(IPlayerCombatActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerCombatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerCombatActionsCallbackInterfaces.Add(instance);
            @IsFire.started += instance.OnIsFire;
            @IsFire.performed += instance.OnIsFire;
            @IsFire.canceled += instance.OnIsFire;
            @IsAim.started += instance.OnIsAim;
            @IsAim.performed += instance.OnIsAim;
            @IsAim.canceled += instance.OnIsAim;
            @IsReload.started += instance.OnIsReload;
            @IsReload.performed += instance.OnIsReload;
            @IsReload.canceled += instance.OnIsReload;
            @SwitchWeapon.started += instance.OnSwitchWeapon;
            @SwitchWeapon.performed += instance.OnSwitchWeapon;
            @SwitchWeapon.canceled += instance.OnSwitchWeapon;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerCombatActions" />
        private void UnregisterCallbacks(IPlayerCombatActions instance)
        {
            @IsFire.started -= instance.OnIsFire;
            @IsFire.performed -= instance.OnIsFire;
            @IsFire.canceled -= instance.OnIsFire;
            @IsAim.started -= instance.OnIsAim;
            @IsAim.performed -= instance.OnIsAim;
            @IsAim.canceled -= instance.OnIsAim;
            @IsReload.started -= instance.OnIsReload;
            @IsReload.performed -= instance.OnIsReload;
            @IsReload.canceled -= instance.OnIsReload;
            @SwitchWeapon.started -= instance.OnSwitchWeapon;
            @SwitchWeapon.performed -= instance.OnSwitchWeapon;
            @SwitchWeapon.canceled -= instance.OnSwitchWeapon;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerCombatActions.UnregisterCallbacks(IPlayerCombatActions)" />.
        /// </summary>
        /// <seealso cref="PlayerCombatActions.UnregisterCallbacks(IPlayerCombatActions)" />
        public void RemoveCallbacks(IPlayerCombatActions instance)
        {
            if (m_Wrapper.m_PlayerCombatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerCombatActions.AddCallbacks(IPlayerCombatActions)" />
        /// <seealso cref="PlayerCombatActions.RemoveCallbacks(IPlayerCombatActions)" />
        /// <seealso cref="PlayerCombatActions.UnregisterCallbacks(IPlayerCombatActions)" />
        public void SetCallbacks(IPlayerCombatActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerCombatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerCombatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerCombatActions" /> instance referencing this action map.
    /// </summary>
    public PlayerCombatActions @PlayerCombat => new PlayerCombatActions(this);

    // PlayerSkill
    private readonly InputActionMap m_PlayerSkill;
    private List<IPlayerSkillActions> m_PlayerSkillActionsCallbackInterfaces = new List<IPlayerSkillActions>();
    private readonly InputAction m_PlayerSkill_IsSkill1;
    private readonly InputAction m_PlayerSkill_IsSkill2;
    private readonly InputAction m_PlayerSkill_IsSkill3;
    private readonly InputAction m_PlayerSkill_IsSkill4;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerSkill".
    /// </summary>
    public struct PlayerSkillActions
    {
        private @MyInputSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerSkillActions(@MyInputSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerSkill/IsSkill1".
        /// </summary>
        public InputAction @IsSkill1 => m_Wrapper.m_PlayerSkill_IsSkill1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerSkill/IsSkill2".
        /// </summary>
        public InputAction @IsSkill2 => m_Wrapper.m_PlayerSkill_IsSkill2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerSkill/IsSkill3".
        /// </summary>
        public InputAction @IsSkill3 => m_Wrapper.m_PlayerSkill_IsSkill3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerSkill/IsSkill4".
        /// </summary>
        public InputAction @IsSkill4 => m_Wrapper.m_PlayerSkill_IsSkill4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerSkill; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerSkillActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerSkillActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerSkillActions" />
        public void AddCallbacks(IPlayerSkillActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerSkillActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerSkillActionsCallbackInterfaces.Add(instance);
            @IsSkill1.started += instance.OnIsSkill1;
            @IsSkill1.performed += instance.OnIsSkill1;
            @IsSkill1.canceled += instance.OnIsSkill1;
            @IsSkill2.started += instance.OnIsSkill2;
            @IsSkill2.performed += instance.OnIsSkill2;
            @IsSkill2.canceled += instance.OnIsSkill2;
            @IsSkill3.started += instance.OnIsSkill3;
            @IsSkill3.performed += instance.OnIsSkill3;
            @IsSkill3.canceled += instance.OnIsSkill3;
            @IsSkill4.started += instance.OnIsSkill4;
            @IsSkill4.performed += instance.OnIsSkill4;
            @IsSkill4.canceled += instance.OnIsSkill4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerSkillActions" />
        private void UnregisterCallbacks(IPlayerSkillActions instance)
        {
            @IsSkill1.started -= instance.OnIsSkill1;
            @IsSkill1.performed -= instance.OnIsSkill1;
            @IsSkill1.canceled -= instance.OnIsSkill1;
            @IsSkill2.started -= instance.OnIsSkill2;
            @IsSkill2.performed -= instance.OnIsSkill2;
            @IsSkill2.canceled -= instance.OnIsSkill2;
            @IsSkill3.started -= instance.OnIsSkill3;
            @IsSkill3.performed -= instance.OnIsSkill3;
            @IsSkill3.canceled -= instance.OnIsSkill3;
            @IsSkill4.started -= instance.OnIsSkill4;
            @IsSkill4.performed -= instance.OnIsSkill4;
            @IsSkill4.canceled -= instance.OnIsSkill4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerSkillActions.UnregisterCallbacks(IPlayerSkillActions)" />.
        /// </summary>
        /// <seealso cref="PlayerSkillActions.UnregisterCallbacks(IPlayerSkillActions)" />
        public void RemoveCallbacks(IPlayerSkillActions instance)
        {
            if (m_Wrapper.m_PlayerSkillActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerSkillActions.AddCallbacks(IPlayerSkillActions)" />
        /// <seealso cref="PlayerSkillActions.RemoveCallbacks(IPlayerSkillActions)" />
        /// <seealso cref="PlayerSkillActions.UnregisterCallbacks(IPlayerSkillActions)" />
        public void SetCallbacks(IPlayerSkillActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerSkillActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerSkillActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerSkillActions" /> instance referencing this action map.
    /// </summary>
    public PlayerSkillActions @PlayerSkill => new PlayerSkillActions(this);

    // PlayerTeam
    private readonly InputActionMap m_PlayerTeam;
    private List<IPlayerTeamActions> m_PlayerTeamActionsCallbackInterfaces = new List<IPlayerTeamActions>();
    private readonly InputAction m_PlayerTeam_IsSwitchAI1;
    private readonly InputAction m_PlayerTeam_IsSwitchAI2;
    private readonly InputAction m_PlayerTeam_IsSwitchAI3;
    private readonly InputAction m_PlayerTeam_IsSwitchAI4;
    private readonly InputAction m_PlayerTeam_IsSwitchNextCharacter;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerTeam".
    /// </summary>
    public struct PlayerTeamActions
    {
        private @MyInputSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerTeamActions(@MyInputSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerTeam/IsSwitchAI1".
        /// </summary>
        public InputAction @IsSwitchAI1 => m_Wrapper.m_PlayerTeam_IsSwitchAI1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerTeam/IsSwitchAI2".
        /// </summary>
        public InputAction @IsSwitchAI2 => m_Wrapper.m_PlayerTeam_IsSwitchAI2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerTeam/IsSwitchAI3".
        /// </summary>
        public InputAction @IsSwitchAI3 => m_Wrapper.m_PlayerTeam_IsSwitchAI3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerTeam/IsSwitchAI4".
        /// </summary>
        public InputAction @IsSwitchAI4 => m_Wrapper.m_PlayerTeam_IsSwitchAI4;
        /// <summary>
        /// Provides access to the underlying input action "PlayerTeam/IsSwitchNextCharacter".
        /// </summary>
        public InputAction @IsSwitchNextCharacter => m_Wrapper.m_PlayerTeam_IsSwitchNextCharacter;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerTeam; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerTeamActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerTeamActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerTeamActions" />
        public void AddCallbacks(IPlayerTeamActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTeamActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTeamActionsCallbackInterfaces.Add(instance);
            @IsSwitchAI1.started += instance.OnIsSwitchAI1;
            @IsSwitchAI1.performed += instance.OnIsSwitchAI1;
            @IsSwitchAI1.canceled += instance.OnIsSwitchAI1;
            @IsSwitchAI2.started += instance.OnIsSwitchAI2;
            @IsSwitchAI2.performed += instance.OnIsSwitchAI2;
            @IsSwitchAI2.canceled += instance.OnIsSwitchAI2;
            @IsSwitchAI3.started += instance.OnIsSwitchAI3;
            @IsSwitchAI3.performed += instance.OnIsSwitchAI3;
            @IsSwitchAI3.canceled += instance.OnIsSwitchAI3;
            @IsSwitchAI4.started += instance.OnIsSwitchAI4;
            @IsSwitchAI4.performed += instance.OnIsSwitchAI4;
            @IsSwitchAI4.canceled += instance.OnIsSwitchAI4;
            @IsSwitchNextCharacter.started += instance.OnIsSwitchNextCharacter;
            @IsSwitchNextCharacter.performed += instance.OnIsSwitchNextCharacter;
            @IsSwitchNextCharacter.canceled += instance.OnIsSwitchNextCharacter;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerTeamActions" />
        private void UnregisterCallbacks(IPlayerTeamActions instance)
        {
            @IsSwitchAI1.started -= instance.OnIsSwitchAI1;
            @IsSwitchAI1.performed -= instance.OnIsSwitchAI1;
            @IsSwitchAI1.canceled -= instance.OnIsSwitchAI1;
            @IsSwitchAI2.started -= instance.OnIsSwitchAI2;
            @IsSwitchAI2.performed -= instance.OnIsSwitchAI2;
            @IsSwitchAI2.canceled -= instance.OnIsSwitchAI2;
            @IsSwitchAI3.started -= instance.OnIsSwitchAI3;
            @IsSwitchAI3.performed -= instance.OnIsSwitchAI3;
            @IsSwitchAI3.canceled -= instance.OnIsSwitchAI3;
            @IsSwitchAI4.started -= instance.OnIsSwitchAI4;
            @IsSwitchAI4.performed -= instance.OnIsSwitchAI4;
            @IsSwitchAI4.canceled -= instance.OnIsSwitchAI4;
            @IsSwitchNextCharacter.started -= instance.OnIsSwitchNextCharacter;
            @IsSwitchNextCharacter.performed -= instance.OnIsSwitchNextCharacter;
            @IsSwitchNextCharacter.canceled -= instance.OnIsSwitchNextCharacter;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerTeamActions.UnregisterCallbacks(IPlayerTeamActions)" />.
        /// </summary>
        /// <seealso cref="PlayerTeamActions.UnregisterCallbacks(IPlayerTeamActions)" />
        public void RemoveCallbacks(IPlayerTeamActions instance)
        {
            if (m_Wrapper.m_PlayerTeamActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerTeamActions.AddCallbacks(IPlayerTeamActions)" />
        /// <seealso cref="PlayerTeamActions.RemoveCallbacks(IPlayerTeamActions)" />
        /// <seealso cref="PlayerTeamActions.UnregisterCallbacks(IPlayerTeamActions)" />
        public void SetCallbacks(IPlayerTeamActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTeamActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTeamActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerTeamActions" /> instance referencing this action map.
    /// </summary>
    public PlayerTeamActions @PlayerTeam => new PlayerTeamActions(this);

    // PlayerInteraction
    private readonly InputActionMap m_PlayerInteraction;
    private List<IPlayerInteractionActions> m_PlayerInteractionActionsCallbackInterfaces = new List<IPlayerInteractionActions>();
    private readonly InputAction m_PlayerInteraction_IsPickUp;
    private readonly InputAction m_PlayerInteraction_IsOpenOrCloseBag;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerInteraction".
    /// </summary>
    public struct PlayerInteractionActions
    {
        private @MyInputSystem m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerInteractionActions(@MyInputSystem wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerInteraction/IsPickUp".
        /// </summary>
        public InputAction @IsPickUp => m_Wrapper.m_PlayerInteraction_IsPickUp;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInteraction/IsOpenOrCloseBag".
        /// </summary>
        public InputAction @IsOpenOrCloseBag => m_Wrapper.m_PlayerInteraction_IsOpenOrCloseBag;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerInteraction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerInteractionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerInteractionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerInteractionActions" />
        public void AddCallbacks(IPlayerInteractionActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInteractionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInteractionActionsCallbackInterfaces.Add(instance);
            @IsPickUp.started += instance.OnIsPickUp;
            @IsPickUp.performed += instance.OnIsPickUp;
            @IsPickUp.canceled += instance.OnIsPickUp;
            @IsOpenOrCloseBag.started += instance.OnIsOpenOrCloseBag;
            @IsOpenOrCloseBag.performed += instance.OnIsOpenOrCloseBag;
            @IsOpenOrCloseBag.canceled += instance.OnIsOpenOrCloseBag;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerInteractionActions" />
        private void UnregisterCallbacks(IPlayerInteractionActions instance)
        {
            @IsPickUp.started -= instance.OnIsPickUp;
            @IsPickUp.performed -= instance.OnIsPickUp;
            @IsPickUp.canceled -= instance.OnIsPickUp;
            @IsOpenOrCloseBag.started -= instance.OnIsOpenOrCloseBag;
            @IsOpenOrCloseBag.performed -= instance.OnIsOpenOrCloseBag;
            @IsOpenOrCloseBag.canceled -= instance.OnIsOpenOrCloseBag;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerInteractionActions.UnregisterCallbacks(IPlayerInteractionActions)" />.
        /// </summary>
        /// <seealso cref="PlayerInteractionActions.UnregisterCallbacks(IPlayerInteractionActions)" />
        public void RemoveCallbacks(IPlayerInteractionActions instance)
        {
            if (m_Wrapper.m_PlayerInteractionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerInteractionActions.AddCallbacks(IPlayerInteractionActions)" />
        /// <seealso cref="PlayerInteractionActions.RemoveCallbacks(IPlayerInteractionActions)" />
        /// <seealso cref="PlayerInteractionActions.UnregisterCallbacks(IPlayerInteractionActions)" />
        public void SetCallbacks(IPlayerInteractionActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInteractionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInteractionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerInteractionActions" /> instance referencing this action map.
    /// </summary>
    public PlayerInteractionActions @PlayerInteraction => new PlayerInteractionActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerMovement" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerMovementActions.AddCallbacks(IPlayerMovementActions)" />
    /// <seealso cref="PlayerMovementActions.RemoveCallbacks(IPlayerMovementActions)" />
    public interface IPlayerMovementActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsJump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsJump(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerCombat" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerCombatActions.AddCallbacks(IPlayerCombatActions)" />
    /// <seealso cref="PlayerCombatActions.RemoveCallbacks(IPlayerCombatActions)" />
    public interface IPlayerCombatActions
    {
        /// <summary>
        /// Method invoked when associated input action "IsFire" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsFire(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsAim" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsAim(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsReload" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsReload(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchWeapon" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchWeapon(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerSkill" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerSkillActions.AddCallbacks(IPlayerSkillActions)" />
    /// <seealso cref="PlayerSkillActions.RemoveCallbacks(IPlayerSkillActions)" />
    public interface IPlayerSkillActions
    {
        /// <summary>
        /// Method invoked when associated input action "IsSkill1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSkill1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSkill2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSkill2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSkill3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSkill3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSkill4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSkill4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerTeam" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerTeamActions.AddCallbacks(IPlayerTeamActions)" />
    /// <seealso cref="PlayerTeamActions.RemoveCallbacks(IPlayerTeamActions)" />
    public interface IPlayerTeamActions
    {
        /// <summary>
        /// Method invoked when associated input action "IsSwitchAI1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSwitchAI1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSwitchAI2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSwitchAI2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSwitchAI3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSwitchAI3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSwitchAI4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSwitchAI4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsSwitchNextCharacter" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsSwitchNextCharacter(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerInteraction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerInteractionActions.AddCallbacks(IPlayerInteractionActions)" />
    /// <seealso cref="PlayerInteractionActions.RemoveCallbacks(IPlayerInteractionActions)" />
    public interface IPlayerInteractionActions
    {
        /// <summary>
        /// Method invoked when associated input action "IsPickUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsPickUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IsOpenOrCloseBag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIsOpenOrCloseBag(InputAction.CallbackContext context);
    }
}
